version: '3' # docker-composeファイルの書式バージョン。最新の’３’を指定（2019/6/27現在）
services:
  my-anaconda: # 任意の名前（ディレクトリ名 + dev がコンテナ名となります）
    build:
      context: .
      dockerfile: Dockerfile
    image: my-anaconda 
    ports:
    - "8888:8888"
    volumes:
    - .:/workdir
